<a href="https://colab.research.google.com/github/GuilhermeRuy97/BootcampDataScienceAlura/blob/main/mod1Aula2BootcampAlura.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# AULA 01 MOD 01

# AULA 02 MOD 01

In [20]:
import pandas as pd

In [21]:
dados = pd.read_csv("/content/tabela.csv", encoding="ISO-8859-1",
                    skiprows = 3, sep =";", skipfooter = 12,
                    thousands = ".", decimal = ",")
dados.head()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  This is separate from the ipykernel package so we can avoid doing imports until

  Unidade da Federaï¿½ï¿½o 1992/Mar  ...     2020/Ago         Total
0            11 Rondï¿½nia        -  ...   3556381.57  9.291297e+08
1                  12 Acre        -  ...            -  4.206680e+08
2              13 Amazonas        -  ...   4726485.73  1.771655e+09
3               14 Roraima        -  ...   1524478.04  3.050109e+08
4                15 Parï¿½        -  ...  11559714.54  4.437116e+09

[5 rows x 280 columns]

In [22]:
#Eh necessario passar dois colchetes ao passar mais de uma coluna
dados[["2008/Ago", "2008/Set"]].head()

      2008/Ago     2008/Set
0   2938286.29   2843930.91
1   1886871.84   2084884.80
2   8331763.97   8148089.92
3   1045291.11   1003740.89
4  23259148.28  23667690.01

In [23]:
#A media ignora os valores vazios antes que estao antes de 2007
dados.mean()

2007/Ago    3.049528e+05
2007/Set    7.881453e+05
2007/Out    2.440163e+06
2007/Nov    5.517354e+06
2007/Dez    1.233716e+07
                ...
2020/Abr    4.000568e+07
2020/Mai    4.676903e+07
2020/Jun    4.536735e+07
2020/Jul    4.071708e+07
Total       5.993724e+09
Length: 157, dtype: float64

In [26]:
#Ao fazer as colunas usaveis excluimos a unidade da federacao.
#Precisamos entao adiciona-la dnv, porém, precisamos transformar em lista
#antes para podermos inseri-la pois o index eh uma serie imutavel
colunas_usaveis = dados.mean().index.tolist()
colunas_usaveis.insert(0, "Unidade da Federaï¿½ï¿½o")
colunas_usaveis

['Unidade da Federaï¿½ï¿½o',
 '2007/Ago',
 '2007/Set',
 '2007/Out',
 '2007/Nov',
 '2007/Dez',
 '2008/Jan',
 '2008/Fev',
 '2008/Mar',
 '2008/Abr',
 '2008/Mai',
 '2008/Jun',
 '2008/Jul',
 '2008/Ago',
 '2008/Set',
 '2008/Out',
 '2008/Nov',
 '2008/Dez',
 '2009/Jan',
 '2009/Fev',
 '2009/Mar',
 '2009/Abr',
 '2009/Mai',
 '2009/Jun',
 '2009/Jul',
 '2009/Ago',
 '2009/Set',
 '2009/Out',
 '2009/Nov',
 '2009/Dez',
 '2010/Jan',
 '2010/Fev',
 '2010/Mar',
 '2010/Abr',
 '2010/Mai',
 '2010/Jun',
 '2010/Jul',
 '2010/Ago',
 '2010/Set',
 '2010/Out',
 '2010/Nov',
 '2010/Dez',
 '2011/Jan',
 '2011/Fev',
 '2011/Mar',
 '2011/Abr',
 '2011/Mai',
 '2011/Jun',
 '2011/Jul',
 '2011/Ago',
 '2011/Set',
 '2011/Out',
 '2011/Nov',
 '2011/Dez',
 '2012/Jan',
 '2012/Fev',
 '2012/Mar',
 '2012/Abr',
 '2012/Mai',
 '2012/Jun',
 '2012/Jul',
 '2012/Ago',
 '2012/Set',
 '2012/Out',
 '2012/Nov',
 '2012/Dez',
 '2013/Jan',
 '2013/Fev',
 '2013/Mar',
 '2013/Abr',
 '2013/Mai',
 '2013/Jun',
 '2013/Jul',
 '2013/Ago',
 '2013/Set',
 '2013/Out',
 '2013/Nov',
 '2013/Dez',
 '2014/Jan',
 '2014/Fev',
 '2014/Mar',
 '2014/Abr',
 '2014/Mai',
 '2014/Jun',
 '2014/Jul',
 '2014/Ago',
 '2014/Set',
 '2014/Out',
 '2014/Nov',
 '2014/Dez',
 '2015/Jan',
 '2015/Fev',
 '2015/Mar',
 '2015/Abr',
 '2015/Mai',
 '2015/Jun',
 '2015/Jul',
 '2015/Ago',
 '2015/Set',
 '2015/Out',
 '2015/Nov',
 '2015/Dez',
 '2016/Jan',
 '2016/Fev',
 '2016/Mar',
 '2016/Abr',
 '2016/Mai',
 '2016/Jun',
 '2016/Jul',
 '2016/Ago',
 '2016/Set',
 '2016/Out',
 '2016/Nov',
 '2016/Dez',
 '2017/Jan',
 '2017/Fev',
 '2017/Mar',
 '2017/Abr',
 '2017/Mai',
 '2017/Jun',
 '2017/Jul',
 '2017/Ago',
 '2017/Set',
 '2017/Out',
 '2017/Nov',
 '2017/Dez',
 '2018/Jan',
 '2018/Fev',
 '2018/Mar',
 '2018/Abr',
 '2018/Mai',
 '2018/Jun',
 '2018/Jul',
 '2018/Ago',
 '2018/Set',
 '2018/Out',
 '2018/Nov',
 '2018/Dez',
 '2019/Jan',
 '2019/Fev',
 '2019/Mar',
 '2019/Abr',
 '2019/Mai',
 '2019/Jun',
 '2019/Jul',
 '2019/Ago',
 '2019/Set',
 '2019/Out',
 '2019/Nov',
 '2019/Dez',
 '2020/Jan',
 '2020/Fev',
 '2020/Mar',
 '2020/Abr',
 '2020/Mai',
 '2020/Jun',
 '2020/Jul',
 'Total']

In [28]:
usaveis = dados[colunas_usaveis].head()
usaveis

  Unidade da Federaï¿½ï¿½o   2007/Ago  ...     2020/Jul         Total
0            11 Rondï¿½nia    4209.37  ...   7407388.24  9.291297e+08
1                  12 Acre   10470.07  ...   1163813.08  4.206680e+08
2              13 Amazonas   35752.72  ...  13358514.02  1.771655e+09
3               14 Roraima    4785.91  ...   2739498.41  3.050109e+08
4                15 Parï¿½  181159.29  ...  27618727.51  4.437116e+09

[5 rows x 158 columns]

In [30]:
#Nota-se que o index está como um número (0,1,2...etc) e não como a unidade
#da federação, então usa-se set_index("Unidade da Federação")
usaveis.set_index("Unidade da Federaï¿½ï¿½o")

                           2007/Ago   2007/Set  ...     2020/Jul         Total
Unidade da Federaï¿½ï¿½o                        ...
11 Rondï¿½nia               4209.37   16397.03  ...   7407388.24  9.291297e+08
12 Acre                    10470.07   14001.71  ...   1163813.08  4.206680e+08
13 Amazonas                35752.72   45570.64  ...  13358514.02  1.771655e+09
14 Roraima                  4785.91   11858.63  ...   2739498.41  3.050109e+08
15 Parï¿½                 181159.29  433414.74  ...  27618727.51  4.437116e+09

[5 rows x 157 columns]

In [32]:
#Para ver uma coluna só
usaveis["2019/Ago"].head()

0     8909111.89
1     2981072.98
2    16493719.52
3     3181321.82
4    36462011.47
Name: 2019/Ago, dtype: float64

In [40]:
#Para localizar uma linha cujo indice é Acre
#O erro no arquivo nos impede de ver, mas funcionaria
usaveis.loc["12 Acre"]

KeyError: ignored

In [44]:
#Plotar usaveis em um tamanho 12 por 6 com uma transposição T (as colunas viram
#os estados e as linhas os valores)
usaveis.T.plot(figsize=(10,6))

TypeError: ignored

In [ ]:
#Precisamos remover a linha total para poder plotar um gráfico melhor
#"Procure no eixo 1 (eixo da coluna) a linha total"
usaveis.drop("Total",axis = 1)

Refazer aula quando o TABNET voltar